### ISSUE TITLE
Remove `alpha` patch

### ISSUE THREAD

**Issue by paniash** [paniash/st#1]
Currently this build has `alpha` set to 1.0. At this point, it's useless to have the patch in the build.

**Comment by paniash** [comment]
This has been reported [here](https://github.com/LukeSmithxyz/st/issues/306).

**Comment by paniash** [comment]
Any advice @bakkeby?

**Comment by bakkeby** [comment]
The alpha patch applied is likely to be this one:
https://st.suckless.org/patches/alpha/st-alpha-0.8.2.diff

The thing is there's more bespoke things attached on top of it like the `changealpha` function.

If you really want to de-patch then I'd recommend starting by undoing whatever the main alpha patch introduces, then have a closer look at the code that fails to compile after that.

Given that you are taking a version of st that you do not personally maintain yourself it is by far easier to just set the alpha to be opaque as you have already done. There will be things in there that you do not need in either case so why would you seek minimalism if you already take a "bloated" version of st?

The alternative would of course be to start from scratch with a bare st v0.8.4 (or latest master).

**Comment by paniash** [comment]
@bakkeby Thanks for the insight!

> If you really want to de-patch then I'd recommend starting by undoing whatever the main alpha patch introduces, then have a closer look at the code that fails to compile after that.

I'll go ahead with this approach.

> There will be things in there that you do not need in either case so why would you seek minimalism if you already take a "bloated" version of st?

Considering the patches already into the original "bloated" build, I've removed all unnecessary patches except the alpha patch. Sure there are certain bespoke things which I do not understand but I certainly do appreciate the quirks given that the build is objectively better than my original build (which I patched from scratch).

**Comment by paniash** [comment]
I tried your approach and simply undoing the changes by the original alpha diff and removing the `changealpha` function seems to have worked! (Although there are certain instances of the word "alpha" in `x.c` but works nonetheless). 😃

Thanks a lot!
